### ISSUE TITLE
Transactie geeft onjuiste status terug

### ISSUE THREAD

**Issue by Woutje99** [nocksapp/nocks-sdk-php#23]
Er wordt bij bij Nocks een transactie aangemaakt met een `responseUrl`. De transactie wordt gecancelled en ik krijg de `transactionId` teruggestuurd. Op dat moment haal ik via `getTransaction` de transactie op maar dan staat er dat die nog pending is, terwijl de transactie in een ander scherm al op cancelled staat.

**Comment by nocksapp** [comment]
Hoi Wouter,

Bedankt voor je melding, ik heb nog wel een paar vragen om een beter beeld van jouw situatie te krijgen;

- Hoe wordt de transactie gecancelled? Met de `cancelTransaction` functie van de SDK?
- Op welke scherm precies is de transactie wel al op `cancelled`? Is dit een pagina binnen jouw eigen app als redirect na de `cancelTransaction` bijvoorbeeld?

Hoor het graag!

**Comment by Woutje99** [comment]
He!

De transactie wordt inderdaad gecanceld door de `cancelTransaction` functie van de SDK. 
Na het cancellen van de transactie krijg ik de JSON output te zien van die functie, daarop is te zien dat hij cancelled is. Die pagina is binnen mijn app maar komt wel van de SDK terug.

Hopelijk kun je wat met deze informatie!

**Comment by nocksapp** [comment]
Dank voor je snelle reactie. We gaan het bekijken!

**Comment by nocksapp** [comment]
Hoi Wouter,

Ik heb het probleem nader bekeken en 1 wijziging gemaakt in onze API die dit probleem mogelijk zou kunnen oplossen. Namelijk het clearen van de cache van onze 'Entity manager' voor het ophalen van de nieuwe transactie gegevens bij `getTransaction`.

Met onderstaande code krijg ik het juiste resultaat terug:

```php
require '../vendor/autoload.php';

$nocks = new \Nocks\SDK\Nocks();

$transaction = $nocks->createTransaction('NLG_EUR', 1, 'NL16ABNA0602167736');

$txid = $transaction['success']['transactionId'];

$transactionCancel = $nocks->cancelTransaction($txid);

$transactionGet = $nocks->getTransaction($txid);

var_dump($transaction);
echo '<hr />';
var_dump($transactionCancel);
echo '<hr />';
var_dump($transactionGet);
```

Output:

```
array(1) { ["success"]=> array(14) { ["status"]=> string(7) "pending" ["transactionId"]=> string(32) "3da758f22acadd3c8245552a3057a9ac" ["pair"]=> string(7) "NLG_EUR" ["withdrawal"]=> string(18) "NL16ABNA0602167736" ["withdrawalOriginal"]=> string(18) "NL16ABNA0602167736" ["withdrawalAmount"]=> string(4) "1.00" ["withdrawalTransactionId"]=> NULL ["deposit"]=> string(34) "GXDwZsN4XbrXXJFToPbLJYgxA5L3mCcVpm" ["depositAmount"]=> string(8) "24.87726" ["depositTransactionId"]=> NULL ["expiration"]=> string(19) "2017-05-30 23:03:10" ["expirationTimestamp"]=> string(10) "1496178190" ["ipAddress"]=> string(14) "84.104.127.182" ["ipAddressPayment"]=> NULL } } 

array(1) { ["success"]=> array(14) { ["status"]=> string(9) "cancelled" ["transactionId"]=> string(32) "3da758f22acadd3c8245552a3057a9ac" ["pair"]=> string(7) "NLG_EUR" ["withdrawal"]=> string(18) "NL16ABNA0602167736" ["withdrawalOriginal"]=> string(18) "NL16ABNA0602167736" ["withdrawalAmount"]=> string(4) "1.00" ["withdrawalTransactionId"]=> NULL ["deposit"]=> string(34) "GXDwZsN4XbrXXJFToPbLJYgxA5L3mCcVpm" ["depositAmount"]=> string(8) "24.87726" ["depositTransactionId"]=> NULL ["expiration"]=> string(19) "2017-05-30 23:03:10" ["expirationTimestamp"]=> string(10) "1496178190" ["ipAddress"]=> string(14) "84.104.127.182" ["ipAddressPayment"]=> NULL } } 

array(1) { ["success"]=> array(14) { ["status"]=> string(9) "cancelled" ["transactionId"]=> string(32) "3da758f22acadd3c8245552a3057a9ac" ["pair"]=> string(7) "NLG_EUR" ["withdrawal"]=> string(18) "NL16ABNA0602167736" ["withdrawalOriginal"]=> string(18) "NL16ABNA0602167736" ["withdrawalAmount"]=> string(4) "1.00" ["withdrawalTransactionId"]=> NULL ["deposit"]=> string(34) "GXDwZsN4XbrXXJFToPbLJYgxA5L3mCcVpm" ["depositAmount"]=> string(8) "24.87726" ["depositTransactionId"]=> NULL ["expiration"]=> string(19) "2017-05-30 23:03:10" ["expirationTimestamp"]=> string(10) "1496178190" ["ipAddress"]=> string(14) "84.104.127.182" ["ipAddressPayment"]=> NULL } } 
```

Zoals je ziet zijn deze calls zelfs direct na elkaar in het zelfde script, echter kreeg ik dit resultaat ook al voor de aanpassing de API...

Ik hoor graag of het aan jouw kant nu is verholpen!

**Comment by Woutje99** [comment]
Hé,

Ik heb het zojuist opnieuw geprobeerd voor 2 transacties maar krijg opnieuw een verkeerde status terug van de SDK. 

Het voorbeeld dat je geeft heb ik zelf ook uitgevoerd en die geeft wel de juiste status terug.
Wel vreemd omdat de er tussen het cancellen van de transactie en het aanroepen ervan wel 1 á 2 seconden zit, dit is veel korter dan bij het voorbeeld waarin het wel goed gaat.

Zijn er nog andere opties/mogelijkheden?

**Comment by nocksapp** [comment]
Hoi Wouter,

Weet je zeker dat je wel de zelfde transactie opvraagt? Zou je anders het stukje code hier kunnen delen, dan kijk ik even mee of het misschien daar ergens in zit.

**Comment by Woutje99** [comment]
Ik kan zeker even wat code delen. Ik heb de website op een tijdelijke ip-adres neergezet zodat je het kunt zien. Volgens mij heb ik je een Slack bericht gestuurd omdat de website nog niet af is deel ik die liever nog niet publiekelijk.
